# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'Yodle-iOS-Training' do

pod 'UIActivityIndicator-for-SDWebImage', '~> 1.2' #Async downloading of images with spinner

end
