# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'Yodle-iOS-Training' do

pod 'SDWebImage', '~>3.7'
pod "AFNetworking", "~> 2.0"

end

target 'Yodle-iOS-TrainingTests' do

end

